// GENERATED by scripts/generate-frame-manifest.py -- do not edit by hand.
// Slot rects are detected from each PNG's alpha channel (the transparent photo windows).

export type FrameSlot = { x: number; y: number; w: number; h: number };

/** Fully transparent rows/cols at each edge of the artwork; the renderer
 *  clamps the art outward into them so they don't print as white slivers. */
export type FrameBleed = { top: number; bottom: number; left: number; right: number };

export type FrameTheme = {
  key: string;
  label: string;
  photoCount: number;
  single: { src: string; w: number; h: number; slots: FrameSlot[]; bleed: FrameBleed };
  print: {
    src: string;
    w: number;
    h: number;
    slots: { left: FrameSlot[]; right: FrameSlot[] };
    bleed: FrameBleed;
  };
};

export const FRAME_THEMES: FrameTheme[] = [
  {
    "key": "animal",
    "label": "Animals",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/animal pic3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 71,
          "y": 94,
          "w": 470,
          "h": 410
        },
        {
          "x": 54,
          "y": 578,
          "w": 513,
          "h": 431
        },
        {
          "x": 34,
          "y": 1096,
          "w": 538,
          "h": 457
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-animal-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 92,
            "y": 112,
            "w": 440,
            "h": 402
          },
          {
            "x": 84,
            "y": 625,
            "w": 465,
            "h": 401
          },
          {
            "x": 72,
            "y": 1122,
            "w": 479,
            "h": 425
          }
        ],
        "right": [
          {
            "x": 670,
            "y": 112,
            "w": 426,
            "h": 402
          },
          {
            "x": 648,
            "y": 624,
            "w": 466,
            "h": 409
          },
          {
            "x": 639,
            "y": 1122,
            "w": 485,
            "h": 425
          }
        ]
      },
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "animal",
    "label": "Animals",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/animal pic 4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 78,
          "y": 45,
          "w": 456,
          "h": 338
        },
        {
          "x": 63,
          "y": 451,
          "w": 493,
          "h": 331
        },
        {
          "x": 33,
          "y": 825,
          "w": 520,
          "h": 339
        },
        {
          "x": 51,
          "y": 1204,
          "w": 506,
          "h": 347
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-animal-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 97,
            "y": 90,
            "w": 418,
            "h": 316
          },
          {
            "x": 89,
            "y": 469,
            "w": 448,
            "h": 331
          },
          {
            "x": 52,
            "y": 857,
            "w": 487,
            "h": 336
          },
          {
            "x": 62,
            "y": 1237,
            "w": 485,
            "h": 340
          }
        ],
        "right": [
          {
            "x": 707,
            "y": 90,
            "w": 410,
            "h": 316
          },
          {
            "x": 699,
            "y": 470,
            "w": 439,
            "h": 330
          },
          {
            "x": 663,
            "y": 857,
            "w": 477,
            "h": 336
          },
          {
            "x": 673,
            "y": 1237,
            "w": 475,
            "h": 340
          }
        ]
      },
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "apple",
    "label": "Apple",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/apple sale pic2.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 55,
          "y": 68,
          "w": 494,
          "h": 659
        },
        {
          "x": 63,
          "y": 836,
          "w": 496,
          "h": 667
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-apple-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 98,
            "y": 106,
            "w": 428,
            "h": 655
          },
          {
            "x": 94,
            "y": 879,
            "w": 428,
            "h": 652
          }
        ],
        "right": [
          {
            "x": 679,
            "y": 96,
            "w": 428,
            "h": 655
          },
          {
            "x": 675,
            "y": 869,
            "w": 428,
            "h": 652
          }
        ]
      },
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "apple",
    "label": "Apple",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/apple pic3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 60,
          "y": 56,
          "w": 496,
          "h": 416
        },
        {
          "x": 61,
          "y": 566,
          "w": 496,
          "h": 420
        },
        {
          "x": 49,
          "y": 1060,
          "w": 513,
          "h": 457
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-apple-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 75,
            "y": 93,
            "w": 455,
            "h": 418
          },
          {
            "x": 81,
            "y": 597,
            "w": 461,
            "h": 434
          },
          {
            "x": 84,
            "y": 1115,
            "w": 454,
            "h": 411
          }
        ],
        "right": [
          {
            "x": 668,
            "y": 108,
            "w": 455,
            "h": 418
          },
          {
            "x": 674,
            "y": 612,
            "w": 461,
            "h": 434
          },
          {
            "x": 677,
            "y": 1130,
            "w": 454,
            "h": 411
          }
        ]
      },
      "bleed": {
        "top": 18,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "apple",
    "label": "Apple",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/apple sale pic 4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 44,
          "y": 75,
          "w": 496,
          "h": 299
        },
        {
          "x": 50,
          "y": 440,
          "w": 496,
          "h": 315
        },
        {
          "x": 53,
          "y": 824,
          "w": 500,
          "h": 334
        },
        {
          "x": 55,
          "y": 1231,
          "w": 497,
          "h": 299
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-apple-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 91,
            "y": 95,
            "w": 435,
            "h": 298
          },
          {
            "x": 91,
            "y": 484,
            "w": 435,
            "h": 298
          },
          {
            "x": 91,
            "y": 878,
            "w": 435,
            "h": 298
          },
          {
            "x": 91,
            "y": 1269,
            "w": 435,
            "h": 298
          }
        ],
        "right": [
          {
            "x": 664,
            "y": 95,
            "w": 435,
            "h": 298
          },
          {
            "x": 664,
            "y": 484,
            "w": 435,
            "h": 298
          },
          {
            "x": 664,
            "y": 878,
            "w": 435,
            "h": 298
          },
          {
            "x": 664,
            "y": 1269,
            "w": 435,
            "h": 298
          }
        ]
      },
      "bleed": {
        "top": 21,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "basketball",
    "label": "Basketball",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/Basketball pic2.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 39,
          "y": 43,
          "w": 522,
          "h": 723
        },
        {
          "x": 39,
          "y": 816,
          "w": 522,
          "h": 723
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-basketball-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 58,
            "y": 51,
            "w": 504,
            "h": 733
          },
          {
            "x": 58,
            "y": 827,
            "w": 504,
            "h": 733
          }
        ],
        "right": [
          {
            "x": 638,
            "y": 51,
            "w": 504,
            "h": 733
          },
          {
            "x": 638,
            "y": 827,
            "w": 504,
            "h": 733
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "basketball",
    "label": "Basketball",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/basketball pic3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 40,
          "y": 35,
          "w": 532,
          "h": 475
        },
        {
          "x": 40,
          "y": 550,
          "w": 532,
          "h": 475
        },
        {
          "x": 40,
          "y": 1065,
          "w": 532,
          "h": 475
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-basketball-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 58,
            "y": 62,
            "w": 502,
            "h": 475
          },
          {
            "x": 58,
            "y": 577,
            "w": 502,
            "h": 475
          },
          {
            "x": 58,
            "y": 1092,
            "w": 502,
            "h": 475
          }
        ],
        "right": [
          {
            "x": 640,
            "y": 62,
            "w": 491,
            "h": 475
          },
          {
            "x": 640,
            "y": 577,
            "w": 491,
            "h": 475
          },
          {
            "x": 640,
            "y": 1092,
            "w": 491,
            "h": 475
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "basketball",
    "label": "Basketball",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/basketball pic 4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 40,
          "y": 46,
          "w": 532,
          "h": 346
        },
        {
          "x": 40,
          "y": 432,
          "w": 532,
          "h": 346
        },
        {
          "x": 40,
          "y": 818,
          "w": 532,
          "h": 346
        },
        {
          "x": 40,
          "y": 1204,
          "w": 532,
          "h": 346
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-basketball-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 58,
            "y": 79,
            "w": 502,
            "h": 346
          },
          {
            "x": 58,
            "y": 465,
            "w": 502,
            "h": 346
          },
          {
            "x": 58,
            "y": 851,
            "w": 502,
            "h": 346
          },
          {
            "x": 58,
            "y": 1237,
            "w": 502,
            "h": 346
          }
        ],
        "right": [
          {
            "x": 640,
            "y": 79,
            "w": 502,
            "h": 346
          },
          {
            "x": 640,
            "y": 465,
            "w": 502,
            "h": 346
          },
          {
            "x": 640,
            "y": 851,
            "w": 502,
            "h": 346
          },
          {
            "x": 640,
            "y": 1237,
            "w": 502,
            "h": 346
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "brit",
    "label": "Pattern",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/Britan pattern2.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 38,
          "y": 37,
          "w": 532,
          "h": 735
        },
        {
          "x": 38,
          "y": 811,
          "w": 536,
          "h": 737
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-brit-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 62,
            "y": 67,
            "w": 504,
            "h": 733
          },
          {
            "x": 62,
            "y": 841,
            "w": 504,
            "h": 733
          }
        ],
        "right": [
          {
            "x": 634,
            "y": 67,
            "w": 504,
            "h": 733
          },
          {
            "x": 634,
            "y": 841,
            "w": 504,
            "h": 733
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 3,
        "right": 3
      }
    }
  },
  {
    "key": "brit",
    "label": "Pattern",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/brittan pattern 3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 40,
          "y": 35,
          "w": 532,
          "h": 475
        },
        {
          "x": 40,
          "y": 550,
          "w": 532,
          "h": 475
        },
        {
          "x": 40,
          "y": 1065,
          "w": 532,
          "h": 475
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-brit-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 58,
            "y": 63,
            "w": 502,
            "h": 475
          },
          {
            "x": 58,
            "y": 578,
            "w": 502,
            "h": 475
          },
          {
            "x": 58,
            "y": 1093,
            "w": 502,
            "h": 475
          }
        ],
        "right": [
          {
            "x": 640,
            "y": 63,
            "w": 502,
            "h": 475
          },
          {
            "x": 640,
            "y": 578,
            "w": 502,
            "h": 475
          },
          {
            "x": 640,
            "y": 1093,
            "w": 502,
            "h": 475
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "brit",
    "label": "Pattern",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/brittan pic4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 40,
          "y": 46,
          "w": 532,
          "h": 346
        },
        {
          "x": 40,
          "y": 432,
          "w": 532,
          "h": 346
        },
        {
          "x": 40,
          "y": 818,
          "w": 532,
          "h": 346
        },
        {
          "x": 40,
          "y": 1204,
          "w": 532,
          "h": 346
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-brit-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 58,
            "y": 79,
            "w": 502,
            "h": 346
          },
          {
            "x": 58,
            "y": 465,
            "w": 502,
            "h": 346
          },
          {
            "x": 58,
            "y": 851,
            "w": 502,
            "h": 346
          },
          {
            "x": 58,
            "y": 1237,
            "w": 502,
            "h": 346
          }
        ],
        "right": [
          {
            "x": 640,
            "y": 79,
            "w": 502,
            "h": 346
          },
          {
            "x": 640,
            "y": 465,
            "w": 502,
            "h": 346
          },
          {
            "x": 640,
            "y": 851,
            "w": 502,
            "h": 346
          },
          {
            "x": 640,
            "y": 1237,
            "w": 502,
            "h": 346
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "circuit",
    "label": "Circuit",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/circuit2.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 30,
          "y": 26,
          "w": 540,
          "h": 753
        },
        {
          "x": 30,
          "y": 803,
          "w": 552,
          "h": 753
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-circuit-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 50,
            "w": 524,
            "h": 753
          },
          {
            "x": 48,
            "y": 826,
            "w": 524,
            "h": 753
          }
        ],
        "right": [
          {
            "x": 628,
            "y": 50,
            "w": 524,
            "h": 753
          },
          {
            "x": 628,
            "y": 826,
            "w": 524,
            "h": 753
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "circuit",
    "label": "Circuit",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/circuit pic 3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 19,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 534,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 1049,
          "w": 552,
          "h": 495
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-circuit-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "circuit",
    "label": "Circuit",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/circuit pic4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 36,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 422,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 808,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 1194,
          "w": 552,
          "h": 366
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-circuit-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "doodle",
    "label": "Doodles",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/cute doodle pic2.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 30,
          "y": 27,
          "w": 540,
          "h": 751
        },
        {
          "x": 31,
          "y": 804,
          "w": 550,
          "h": 751
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-doodle-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 50,
            "y": 44,
            "w": 518,
            "h": 747
          },
          {
            "x": 50,
            "y": 820,
            "w": 518,
            "h": 747
          }
        ],
        "right": [
          {
            "x": 632,
            "y": 44,
            "w": 518,
            "h": 747
          },
          {
            "x": 632,
            "y": 820,
            "w": 518,
            "h": 747
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "doodle",
    "label": "Doodles",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/cute doodle pic3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 33,
          "y": 35,
          "w": 546,
          "h": 488
        },
        {
          "x": 33,
          "y": 550,
          "w": 546,
          "h": 489
        },
        {
          "x": 33,
          "y": 1065,
          "w": 546,
          "h": 489
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-doodle-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 49,
            "y": 55,
            "w": 516,
            "h": 489
          },
          {
            "x": 49,
            "y": 570,
            "w": 516,
            "h": 489
          },
          {
            "x": 49,
            "y": 1085,
            "w": 516,
            "h": 489
          }
        ],
        "right": [
          {
            "x": 629,
            "y": 55,
            "w": 516,
            "h": 489
          },
          {
            "x": 629,
            "y": 570,
            "w": 516,
            "h": 489
          },
          {
            "x": 630,
            "y": 1085,
            "w": 515,
            "h": 489
          }
        ]
      },
      "bleed": {
        "top": 8,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "doodle",
    "label": "Doodles",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/cute doodle pic 4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 33,
          "y": 39,
          "w": 546,
          "h": 360
        },
        {
          "x": 33,
          "y": 425,
          "w": 546,
          "h": 360
        },
        {
          "x": 33,
          "y": 811,
          "w": 546,
          "h": 360
        },
        {
          "x": 33,
          "y": 1197,
          "w": 546,
          "h": 360
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-doodle-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 55,
            "y": 72,
            "w": 515,
            "h": 360
          },
          {
            "x": 54,
            "y": 458,
            "w": 515,
            "h": 360
          },
          {
            "x": 54,
            "y": 844,
            "w": 516,
            "h": 360
          },
          {
            "x": 54,
            "y": 1230,
            "w": 516,
            "h": 360
          }
        ],
        "right": [
          {
            "x": 638,
            "y": 72,
            "w": 515,
            "h": 360
          },
          {
            "x": 637,
            "y": 458,
            "w": 515,
            "h": 360
          },
          {
            "x": 637,
            "y": 844,
            "w": 516,
            "h": 360
          },
          {
            "x": 637,
            "y": 1230,
            "w": 516,
            "h": 360
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "football",
    "label": "Football",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/baseball pic2.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 30,
          "y": 26,
          "w": 540,
          "h": 753
        },
        {
          "x": 30,
          "y": 803,
          "w": 552,
          "h": 753
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-football-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 41,
            "w": 524,
            "h": 753
          },
          {
            "x": 48,
            "y": 817,
            "w": 524,
            "h": 753
          }
        ],
        "right": [
          {
            "x": 628,
            "y": 41,
            "w": 524,
            "h": 753
          },
          {
            "x": 628,
            "y": 817,
            "w": 524,
            "h": 753
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "football",
    "label": "Football",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/baseball pic3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 19,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 534,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 1049,
          "w": 552,
          "h": 495
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-football-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 46,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 46,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 46,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 51,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 566,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 1081,
            "w": 522,
            "h": 495
          }
        ]
      },
      "bleed": {
        "top": 19,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "football",
    "label": "Football",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/baseball pic4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 36,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 422,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 808,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 1194,
          "w": 552,
          "h": 366
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-football-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ],
        "right": [
          {
            "x": 618,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 618,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 618,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 618,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "lacrosse",
    "label": "Lacrosse",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/lacrosse pic2.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 32,
          "y": 36,
          "w": 538,
          "h": 743
        },
        {
          "x": 32,
          "y": 803,
          "w": 539,
          "h": 744
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-softball-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 41,
            "w": 524,
            "h": 753
          },
          {
            "x": 48,
            "y": 817,
            "w": 524,
            "h": 753
          }
        ],
        "right": [
          {
            "x": 628,
            "y": 40,
            "w": 524,
            "h": 753
          },
          {
            "x": 628,
            "y": 816,
            "w": 524,
            "h": 753
          }
        ]
      },
      "bleed": {
        "top": 19,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "lacrosse",
    "label": "Lacrosse",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/lacrosse pic3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 32,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 547,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 1062,
          "w": 552,
          "h": 495
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-softball-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "lacrosse",
    "label": "Lacrosse",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/lacrosse pic 4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 36,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 422,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 808,
          "w": 526,
          "h": 366
        },
        {
          "x": 30,
          "y": 1194,
          "w": 552,
          "h": 366
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-softball-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 841,
            "w": 476,
            "h": 366
          },
          {
            "x": 48,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 841,
            "w": 500,
            "h": 366
          },
          {
            "x": 630,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "penhall",
    "label": "Penn Hall",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/penhall pic2.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 30,
          "y": 26,
          "w": 540,
          "h": 753
        },
        {
          "x": 30,
          "y": 803,
          "w": 552,
          "h": 753
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-penhall-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 41,
            "w": 504,
            "h": 753
          },
          {
            "x": 48,
            "y": 817,
            "w": 504,
            "h": 753
          }
        ],
        "right": [
          {
            "x": 600,
            "y": 41,
            "w": 504,
            "h": 753
          },
          {
            "x": 600,
            "y": 817,
            "w": 504,
            "h": 753
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 48
      }
    }
  },
  {
    "key": "penhall",
    "label": "Penn Hall",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/pen hall 3 pic.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 32,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 547,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 1062,
          "w": 552,
          "h": 495
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-penhall-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "penhall",
    "label": "Penn Hall",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/pen hall pic 4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 36,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 422,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 808,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 1194,
          "w": 552,
          "h": 366
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-penhall-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "picnic",
    "label": "Picnic",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/Picnic2.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 30,
          "y": 26,
          "w": 540,
          "h": 753
        },
        {
          "x": 30,
          "y": 803,
          "w": 552,
          "h": 753
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-picnic-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 53,
            "y": 53,
            "w": 524,
            "h": 753
          },
          {
            "x": 53,
            "y": 830,
            "w": 524,
            "h": 753
          }
        ],
        "right": [
          {
            "x": 623,
            "y": 53,
            "w": 524,
            "h": 753
          },
          {
            "x": 623,
            "y": 830,
            "w": 524,
            "h": 753
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 5
      }
    }
  },
  {
    "key": "picnic",
    "label": "Picnic",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/picnic 3 strip.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 19,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 534,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 1049,
          "w": 552,
          "h": 495
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-picnic-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ],
        "right": [
          {
            "x": 618,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 618,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 618,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "picnic",
    "label": "Picnic",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/picnic4pic.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 36,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 422,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 808,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 1194,
          "w": 552,
          "h": 366
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-picnic-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "polka",
    "label": "Polka Dot",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/polkadot 2pic.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 43,
          "y": 45,
          "w": 526,
          "h": 726
        },
        {
          "x": 42,
          "y": 816,
          "w": 528,
          "h": 729
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-polkadot-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 70,
            "y": 61,
            "w": 494,
            "h": 725
          },
          {
            "x": 70,
            "y": 829,
            "w": 494,
            "h": 733
          }
        ],
        "right": [
          {
            "x": 636,
            "y": 61,
            "w": 494,
            "h": 725
          },
          {
            "x": 636,
            "y": 829,
            "w": 494,
            "h": 733
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 2,
        "right": 2
      }
    }
  },
  {
    "key": "polka",
    "label": "Polka Dot",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/polka dot pic3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 43,
          "y": 41,
          "w": 527,
          "h": 474
        },
        {
          "x": 40,
          "y": 557,
          "w": 532,
          "h": 475
        },
        {
          "x": 41,
          "y": 1074,
          "w": 529,
          "h": 472
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-polka-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 54,
            "y": 61,
            "w": 511,
            "h": 473
          },
          {
            "x": 58,
            "y": 577,
            "w": 502,
            "h": 475
          },
          {
            "x": 55,
            "y": 1092,
            "w": 503,
            "h": 469
          }
        ],
        "right": [
          {
            "x": 635,
            "y": 61,
            "w": 511,
            "h": 473
          },
          {
            "x": 640,
            "y": 577,
            "w": 502,
            "h": 475
          },
          {
            "x": 642,
            "y": 1092,
            "w": 503,
            "h": 469
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "polka",
    "label": "Polka Dot",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/polka dot4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 39,
          "y": 38,
          "w": 533,
          "h": 352
        },
        {
          "x": 37,
          "y": 428,
          "w": 536,
          "h": 351
        },
        {
          "x": 33,
          "y": 818,
          "w": 544,
          "h": 359
        },
        {
          "x": 36,
          "y": 1208,
          "w": 537,
          "h": 350
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-polka-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 57,
            "y": 78,
            "w": 503,
            "h": 346
          },
          {
            "x": 56,
            "y": 466,
            "w": 507,
            "h": 344
          },
          {
            "x": 51,
            "y": 847,
            "w": 515,
            "h": 353
          },
          {
            "x": 56,
            "y": 1238,
            "w": 505,
            "h": 336
          }
        ],
        "right": [
          {
            "x": 640,
            "y": 78,
            "w": 503,
            "h": 346
          },
          {
            "x": 639,
            "y": 466,
            "w": 507,
            "h": 344
          },
          {
            "x": 634,
            "y": 847,
            "w": 515,
            "h": 353
          },
          {
            "x": 639,
            "y": 1238,
            "w": 505,
            "h": 336
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "soccer",
    "label": "Soccer",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/soccer 2pic.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 35,
          "y": 26,
          "w": 530,
          "h": 742
        },
        {
          "x": 35,
          "y": 803,
          "w": 542,
          "h": 740
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-soccer-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 53,
            "y": 46,
            "w": 504,
            "h": 743
          },
          {
            "x": 53,
            "y": 822,
            "w": 504,
            "h": 743
          }
        ],
        "right": [
          {
            "x": 643,
            "y": 46,
            "w": 504,
            "h": 743
          },
          {
            "x": 643,
            "y": 822,
            "w": 504,
            "h": 743
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "soccer",
    "label": "Soccer",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/soccer pic3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 42,
          "y": 39,
          "w": 532,
          "h": 476
        },
        {
          "x": 42,
          "y": 555,
          "w": 532,
          "h": 476
        },
        {
          "x": 42,
          "y": 1072,
          "w": 532,
          "h": 476
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 1,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-soccer-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 53,
            "y": 57,
            "w": 512,
            "h": 485
          },
          {
            "x": 53,
            "y": 572,
            "w": 512,
            "h": 485
          },
          {
            "x": 53,
            "y": 1087,
            "w": 512,
            "h": 485
          }
        ],
        "right": [
          {
            "x": 623,
            "y": 57,
            "w": 512,
            "h": 485
          },
          {
            "x": 623,
            "y": 572,
            "w": 512,
            "h": 485
          },
          {
            "x": 623,
            "y": 1087,
            "w": 512,
            "h": 485
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "soccer",
    "label": "Soccer",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/soccer pic 4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 40,
          "y": 46,
          "w": 532,
          "h": 346
        },
        {
          "x": 40,
          "y": 432,
          "w": 532,
          "h": 346
        },
        {
          "x": 40,
          "y": 818,
          "w": 532,
          "h": 346
        },
        {
          "x": 40,
          "y": 1204,
          "w": 532,
          "h": 346
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-soccer-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 53,
            "y": 74,
            "w": 512,
            "h": 356
          },
          {
            "x": 53,
            "y": 460,
            "w": 512,
            "h": 356
          },
          {
            "x": 53,
            "y": 846,
            "w": 512,
            "h": 356
          },
          {
            "x": 53,
            "y": 1232,
            "w": 512,
            "h": 356
          }
        ],
        "right": [
          {
            "x": 635,
            "y": 74,
            "w": 512,
            "h": 356
          },
          {
            "x": 635,
            "y": 460,
            "w": 512,
            "h": 356
          },
          {
            "x": 635,
            "y": 846,
            "w": 512,
            "h": 356
          },
          {
            "x": 635,
            "y": 1232,
            "w": 512,
            "h": 356
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "tech",
    "label": "Tech",
    "photoCount": 2,
    "single": {
      "src": "/frames/single/tech2.png",
      "w": 600,
      "h": 1800,
      "slots": [
        {
          "x": 30,
          "y": 26,
          "w": 540,
          "h": 753
        },
        {
          "x": 30,
          "y": 803,
          "w": 552,
          "h": 753
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-tech-2pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 50,
            "w": 498,
            "h": 753
          },
          {
            "x": 48,
            "y": 826,
            "w": 498,
            "h": 753
          }
        ],
        "right": [
          {
            "x": 600,
            "y": 50,
            "w": 498,
            "h": 753
          },
          {
            "x": 600,
            "y": 826,
            "w": 498,
            "h": 753
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 54
      }
    }
  },
  {
    "key": "tech",
    "label": "Tech",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/tech pic3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 32,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 547,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 1062,
          "w": 552,
          "h": 495
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-tech-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 50,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 565,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 1080,
            "w": 522,
            "h": 495
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ]
      },
      "bleed": {
        "top": 18,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "tech",
    "label": "Tech",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/tech pic4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 36,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 422,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 808,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 1194,
          "w": 552,
          "h": 366
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-tech-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 630,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "window",
    "label": "Windows",
    "photoCount": 3,
    "single": {
      "src": "/frames/single/window pic3.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 32,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 547,
          "w": 552,
          "h": 495
        },
        {
          "x": 30,
          "y": 1062,
          "w": 552,
          "h": 495
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-window-3pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 48,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ],
        "right": [
          {
            "x": 630,
            "y": 52,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 567,
            "w": 522,
            "h": 495
          },
          {
            "x": 630,
            "y": 1082,
            "w": 522,
            "h": 495
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  },
  {
    "key": "window",
    "label": "Windows",
    "photoCount": 4,
    "single": {
      "src": "/frames/single/window pic 4.png",
      "w": 612,
      "h": 1804,
      "slots": [
        {
          "x": 30,
          "y": 36,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 422,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 808,
          "w": 552,
          "h": 366
        },
        {
          "x": 30,
          "y": 1194,
          "w": 552,
          "h": 366
        }
      ],
      "bleed": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    },
    "print": {
      "src": "/frames/print/backend-window-4pic.png",
      "w": 1200,
      "h": 1800,
      "slots": {
        "left": [
          {
            "x": 48,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 48,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ],
        "right": [
          {
            "x": 629,
            "y": 69,
            "w": 522,
            "h": 366
          },
          {
            "x": 629,
            "y": 455,
            "w": 522,
            "h": 366
          },
          {
            "x": 629,
            "y": 841,
            "w": 522,
            "h": 366
          },
          {
            "x": 629,
            "y": 1227,
            "w": 522,
            "h": 366
          }
        ]
      },
      "bleed": {
        "top": 20,
        "bottom": 0,
        "left": 0,
        "right": 0
      }
    }
  }
];

export function framesForCount(count: number): FrameTheme[] {
  return FRAME_THEMES.filter((t) => t.photoCount === count);
}

export function findFrame(key: string, count: number): FrameTheme | undefined {
  return FRAME_THEMES.find((t) => t.key === key && t.photoCount === count);
}
